

import All from "./Components/All";



export const metadata = {
  title: 'Glods Gym',
  description: 'Generated by create next app',
}





export default  function Home() {
  return (
    <div className="home">
        <All ></All>
    </div>
  )
}
