


import { fetchData , options } from "./FetchCostum"
import BodyPart from "./Components/BodyPart";

export const metadata = {
  title: 'Glods Gym',
  description: 'Generated by create next app',
}





export default async function Home() {
  const arr = []
   const data = await fetchData('https://exercisedb.p.rapidapi.com/exercises/bodyPartList' , options)
   arr.push("all" , ...data)


  return (
    <div className="home">
      <div className="stage-1">
        <div className="con">
        <h1>fitness club</h1>
          <h1>sweat , smile and reapet</h1>
          <h3>check out the most effective exersicses personalized to you </h3>
          <a href="#Exercises">explore exercises</a>
        </div>
        </div>
        <div className="stage-2">
          <div className="container">
            <h2>awesome exercises you should know</h2>
            <div className="flex">
              <input type="text" placeholder="search exercises" />
              <button>search</button>
            </div>
          </div>
        </div>
        <BodyPart arr={arr}/>
    </div>
  )
}
